<?php


register_post_type('redirect', array(
    'name' => 'redirect',
    'label' => 'Redirect',
    'active' => true,
    'description' => '',
    'hierarchical' => false,
    'supports' => array(
        'title',
        'thumbnail',
        'excerpt',
    ),
    'taxonomies' => array(),
    'public' => true,
    'exclude_from_search' => true,
    'publicly_queryable' => true,
    'can_export' => true,
    'delete_with_user' => null,
    'labels' => array(),
    'menu_position' => '',
    'menu_icon' => 'dashicons-update-alt',
    'show_ui' => true,
    'show_in_menu' => true,
    'show_in_nav_menus' => true,
    'show_in_admin_bar' => true,
    'has_archive' => false,
    'rewrite' => array(
        'slug' => '',
        'with_front' => false,
        'feeds' => false,
        'pages' => false,
    ),
    'capability_type' => 'page',
    'capabilities' => array(),
    'map_meta_cap' => null,
    'show_in_rest' => false,
    'rest_base' => '',
    'rest_controller_class' => 'WP_REST_Posts_Controller',
    'acfe_archive_template' => '',
    'acfe_archive_ppp' => 10,
    'acfe_archive_orderby' => 'date',
    'acfe_archive_order' => 'DESC',
    'acfe_archive_meta_key' => '',
    'acfe_archive_meta_type' => '',
    'acfe_single_template' => 'single-redirect.php',
    'acfe_admin_archive' => false,
    'acfe_admin_ppp' => 10,
    'acfe_admin_orderby' => 'date',
    'acfe_admin_order' => 'DESC',
    'acfe_admin_meta_key' => '',
    'acfe_admin_meta_type' => '',
));