<?php

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
		'key' => 'group_64dd008d2817d',
		'title' => 'Lottie / Motion',
		'fields' => array(
			array(
				'key' => 'field_64dd1aaf8aa44',
				'label' => '(Column 4/12)',
				'name' => '',
				'aria-label' => '',
				'type' => 'acfe_column',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'columns' => '4/12',
				'endpoint' => 0,
				'acfe_permissions' => '',
			),
			array(
				'key' => 'field_64dd008d2daad',
				'label' => 'Column Placement',
				'name' => 'column_placement',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'acfe_seamless_style' => 1,
				'acfe_settings' => '',
				'acfe_permissions' => '',
				'acfe_group_modal' => 0,
				'acfe_group_modal_close' => 0,
				'acfe_group_modal_button' => '',
				'acfe_group_modal_size' => 'large',
				'sub_fields' => array(
					array(
						'key' => 'field_64dd008d35370',
						'label' => '',
						'name' => 'column_settings',
						'aria-label' => '',
						'type' => 'clone',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'clone' => array(
							0 => 'group_650fa810896db',
						),
						'display' => 'seamless',
						'layout' => 'block',
						'prefix_label' => 0,
						'prefix_name' => 0,
						'acfe_settings' => '',
						'acfe_permissions' => '',
						'acfe_seamless_style' => 0,
						'acfe_clone_modal' => 0,
						'acfe_clone_modal_close' => 0,
						'acfe_clone_modal_button' => '',
						'acfe_clone_modal_size' => 'large',
					),
				),
			),
			array(
				'key' => 'field_64dd11248aa41',
				'label' => 'Main Options',
				'name' => 'main_options',
				'aria-label' => '',
				'type' => 'checkbox',
				'instructions' => 'Select each option to enable.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'autoplay' => 'autoplay',
					'controls' => 'controls',
					'hover' => 'hover',
					'loop' => 'loop',
				),
				'default_value' => array(
					0 => 'autoplay',
				),
				'return_format' => 'value',
				'acfe_settings' => '',
				'acfe_validate' => '',
				'allow_custom' => 0,
				'acfe_permissions' => '',
				'layout' => 'vertical',
				'toggle' => 0,
				'save_custom' => 0,
				'custom_choice_button_text' => 'Add new choice',
			),
			array(
				'key' => 'field_64dd1a078aa42',
				'label' => 'background',
				'name' => 'motion_background',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'transparent',
				'enable_opacity' => 0,
				'return_format' => 'string',
				'acfe_settings' => '',
				'acfe_validate' => '',
				'acfe_permissions' => '',
			),
			array(
				'key' => 'field_64dd1a588aa43',
				'label' => 'Speed',
				'name' => 'speed',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 1,
				'acfe_settings' => '',
				'acfe_validate' => '',
				'min' => '',
				'max' => '',
				'acfe_permissions' => '',
				'placeholder' => '',
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_64dd1ac18aa45',
				'label' => '(Column 6/12)',
				'name' => '',
				'aria-label' => '',
				'type' => 'acfe_column',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'columns' => '6/12',
				'endpoint' => 0,
				'acfe_permissions' => '',
			),
			array(
				'key' => 'field_64dd2f6e54322',
				'label' => 'Files',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 1,
				'acfe_permissions' => '',
			),
			array(
				'key' => 'field_64dd010a8aa3e',
				'label' => 'Primary .json',
				'name' => 'primary_json',
				'aria-label' => '',
				'type' => 'file',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'uploader' => '',
				'return_format' => 'url',
				'acfe_settings' => '',
				'acfe_validate' => '',
				'min_size' => '',
				'max_size' => '',
				'mime_types' => '',
				'acfe_permissions' => '',
				'library' => 'all',
			),
			array(
				'key' => 'field_64dd1ad38aa46',
				'label' => 'Mobile .json (optional)',
				'name' => 'mobile_json',
				'aria-label' => '',
				'type' => 'file',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'uploader' => '',
				'return_format' => 'url',
				'acfe_settings' => '',
				'acfe_validate' => '',
				'min_size' => '',
				'max_size' => '',
				'mime_types' => '',
				'acfe_permissions' => '',
				'library' => 'all',
			),
			array(
				'key' => 'field_64dd2f9054323',
				'label' => 'Assets (Optional)',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'acfe_permissions' => '',
			),
			array(
				'key' => 'field_64dd2225a63a3',
				'label' => 'Images',
				'name' => 'images_optional',
				'aria-label' => '',
				'type' => 'gallery',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'acfe_settings' => '',
				'acfe_validate' => '',
				'min' => '',
				'max' => '',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'acfe_permissions' => '',
				'insert' => 'append',
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_64dd2fbb16d7c',
				'label' => 'Control Settings',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_64dd11248aa41',
							'operator' => '==',
							'value' => 'controls',
						),
					),
					array(
						array(
							'field' => 'field_64dd11248aa41',
							'operator' => '==contains',
							'value' => 'controls',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'acfe_permissions' => '',
			),
			array(
				'key' => 'field_64dd300116d7e',
				'label' => 'Toolbar height',
				'name' => 'toolbar_height',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 35,
				'acfe_settings' => '',
				'acfe_validate' => '',
				'min' => '',
				'max' => '',
				'acfe_permissions' => '',
				'placeholder' => '',
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_64dd303716d7f',
				'label' => 'Toolbar background color',
				'name' => 'toolbar_background_color',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'transparent',
				'enable_opacity' => 1,
				'return_format' => 'string',
				'acfe_settings' => '',
				'acfe_validate' => '',
				'acfe_permissions' => '',
			),
			array(
				'key' => 'field_64dd305816d80',
				'label' => 'Toolbar icon color',
				'name' => 'toolbar_icon_color',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#999',
				'enable_opacity' => 0,
				'return_format' => 'string',
				'acfe_settings' => '',
				'acfe_validate' => '',
				'acfe_permissions' => '',
			),
			array(
				'key' => 'field_64dd307a16d81',
				'label' => 'Toolbar icon hover color',
				'name' => 'toolbar_icon_hover_color',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#222',
				'enable_opacity' => 0,
				'return_format' => 'string',
				'acfe_settings' => '',
				'acfe_validate' => '',
				'acfe_permissions' => '',
			),
			array(
				'key' => 'field_64dd308f16d82',
				'label' => 'Toolbar icon active color',
				'name' => 'toolbar_icon_active_color',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#555',
				'enable_opacity' => 0,
				'return_format' => 'string',
				'acfe_settings' => '',
				'acfe_validate' => '',
				'acfe_permissions' => '',
			),
			array(
				'key' => 'field_64dd30a116d83',
				'label' => 'Seeker track color',
				'name' => 'seeker_track_color',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#ccc',
				'enable_opacity' => 0,
				'return_format' => 'string',
				'acfe_settings' => '',
				'acfe_validate' => '',
				'acfe_permissions' => '',
			),
			array(
				'key' => 'field_64dd30bc16d84',
				'label' => 'Seeker thumb color',
				'name' => 'seeker_thumb_color',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'rgba(0, 107, 120, 0.8)',
				'enable_opacity' => 1,
				'return_format' => 'string',
				'acfe_settings' => '',
				'acfe_validate' => '',
				'acfe_permissions' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/supply-lottie-block',
				),
			),
		),
		'menu_order' => -100,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'tooltip',
		'hide_on_screen' => array(
			0 => 'excerpt',
			1 => 'page_attributes',
			2 => 'featured_image',
			3 => 'categories',
			4 => 'tags',
		),
		'active' => true,
		'description' => '',
		'show_in_rest' => 1,
		'acfe_display_title' => '',
		'acfe_autosync' => '',
		'acfe_permissions' => '',
		'acfe_form' => 1,
		'acfe_meta' => '',
		'acfe_note' => '',
	) );

	acf_add_local_field_group( array(
		'key' => 'group_65aae008c62be',
		'title' => 'Page Header (Block)',
		'fields' => array(
			array(
				'key' => 'field_65aae008cfde3',
				'label' => 'Header type',
				'name' => 'header_type',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'Image' => 'Image',
					'Video' => 'Video',
					'Basic' => 'Basic',
					'carousel' => 'carousel',
				),
				'default_value' => 'Image',
				'return_format' => 'value',
				'multiple' => 0,
				'acfe_settings' => '',
				'acfe_validate' => '',
				'allow_null' => 0,
				'acfe_permissions' => '',
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'allow_custom' => 0,
				'search_placeholder' => '',
			),
			array(
				'key' => 'field_65aae009271d4',
				'label' => 'Video *',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65aae008cfde3',
							'operator' => '==',
							'value' => 'Video',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
				'acfe_permissions' => '',
			),
			array(
				'key' => 'field_65aae0092e953',
				'label' => 'Video',
				'name' => 'header_video',
				'aria-label' => '',
				'type' => 'oembed',
				'instructions' => 'Link to vimeo video',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65aae008cfde3',
							'operator' => '!=',
							'value' => 'Image',
						),
						array(
							'field' => 'field_65aae00954a64',
							'operator' => '!=',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'width' => '',
				'height' => '',
				'acfe_settings' => '',
				'acfe_validate' => '',
				'acfe_permissions' => '',
			),
			array(
				'key' => 'field_65aae0092ae49',
				'label' => 'Video',
				'name' => 'header_video_uploaded',
				'aria-label' => '',
				'type' => 'file',
				'instructions' => 'uploaded video',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65aae008cfde3',
							'operator' => '!=',
							'value' => 'Image',
						),
						array(
							'field' => 'field_65aae00954a64',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'uploader' => '',
				'return_format' => 'url',
				'acfe_settings' => '',
				'acfe_validate' => '',
				'min_size' => '',
				'max_size' => '',
				'mime_types' => '',
				'acfe_permissions' => '',
				'library' => 'all',
			),
			array(
				'key' => 'field_65aae008dec5a',
				'label' => 'Image / Placeholder *',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65aae008cfde3',
							'operator' => '==',
							'value' => 'Image',
						),
					),
					array(
						array(
							'field' => 'field_65aae008cfde3',
							'operator' => '==',
							'value' => 'Video',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
				'acfe_permissions' => '',
			),
			array(
				'key' => 'field_65aae00904bfa',
				'label' => 'Image',
				'name' => 'header_image',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => 'Will sub as \'thumbnail\' image for this page if none is selected.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'uploader' => '',
				'return_format' => 'array',
				'acfe_thumbnail' => 1,
				'acfe_settings' => '',
				'acfe_validate' => '',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'acfe_permissions' => '',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array(
				'key' => 'field_65aae2a30ec7b',
				'label' => 'Mobile',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
				'acfe_permissions' => '',
			),
			array(
				'key' => 'field_65aae0092360f',
				'label' => '',
				'name' => 'header_mobile',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'acfe_group_modal' => 1,
				'acfe_group_modal_close' => 1,
				'acfe_group_modal_button' => 'Mobile Video (optional)',
				'acfe_group_modal_size' => 'large',
				'acfe_settings' => '',
				'acfe_permissions' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_65aae00963631',
						'label' => 'Video',
						'name' => 'video_mobile',
						'aria-label' => '',
						'type' => 'oembed',
						'instructions' => 'Link to Mobile version of vimeo video',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_65aae008cfde3',
									'operator' => '==',
									'value' => 'Video',
								),
								array(
									'field' => 'field_65aae00979a80',
									'operator' => '!=',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_permissions' => '',
						'width' => '',
						'height' => '',
						'acfe_settings' => '',
						'acfe_validate' => '',
					),
					array(
						'key' => 'field_65aae00967086',
						'label' => 'Video',
						'name' => 'video_mobile_uploaded',
						'aria-label' => '',
						'type' => 'file',
						'instructions' => 'Mobile version of uploaded video',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_65aae008cfde3',
									'operator' => '==',
									'value' => 'Video',
								),
								array(
									'field' => 'field_65aae00979a80',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_permissions' => '',
						'uploader' => '',
						'return_format' => 'url',
						'acfe_settings' => '',
						'acfe_validate' => '',
						'min_size' => '',
						'max_size' => '',
						'mime_types' => '',
						'library' => 'all',
					),
					array(
						'key' => 'field_65aae0096abed',
						'label' => 'Placeholder Image',
						'name' => 'placeholder_image',
						'aria-label' => '',
						'type' => 'image',
						'instructions' => 'The image that displays while the video loads. Thumbnail Image',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_permissions' => '',
						'uploader' => '',
						'return_format' => 'array',
						'acfe_thumbnail' => 1,
						'acfe_settings' => '',
						'acfe_validate' => '',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'preview_size' => 'medium',
						'library' => 'all',
					),
					array(
						'key' => 'field_65aae0096e66e',
						'label' => 'Options',
						'name' => 'options',
						'aria-label' => '',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_65aae008cfde3',
									'operator' => '==',
									'value' => 'Video',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_permissions' => '',
						'layout' => 'block',
						'acfe_seamless_style' => 1,
						'acfe_settings' => '',
						'sub_fields' => array(
							array(
								'key' => 'field_65aae00979a80',
								'label' => 'Self host video (Mobile)',
								'name' => 'self_host_video',
								'aria-label' => '',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_65aae008cfde3',
											'operator' => '==',
											'value' => 'Video',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_permissions' => '',
								'message' => 'Self host this video instead of using vimeo?',
								'default_value' => 1,
								'acfe_settings' => '',
								'acfe_validate' => '',
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_65aae0097d52e',
								'label' => '',
								'name' => '',
								'aria-label' => '',
								'type' => 'clone',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_permissions' => '',
								'clone' => array(
									0 => 'group_65a9931fafda9',
								),
								'display' => 'seamless',
								'layout' => 'block',
								'prefix_label' => 0,
								'prefix_name' => 0,
								'acfe_settings' => '',
								'acfe_seamless_style' => 0,
								'acfe_clone_modal' => 0,
								'acfe_clone_modal_close' => 0,
								'acfe_clone_modal_button' => '',
								'acfe_clone_modal_size' => 'large',
							),
						),
						'acfe_group_modal' => 0,
						'acfe_group_modal_close' => 0,
						'acfe_group_modal_button' => '',
						'acfe_group_modal_size' => 'large',
					),
					array(
						'key' => 'field_65aae3730ec80',
						'label' => 'Options',
						'name' => 'options',
						'aria-label' => '',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_65aae008cfde3',
									'operator' => '==',
									'value' => 'Image',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'acfe_seamless_style' => 1,
						'acfe_settings' => '',
						'acfe_permissions' => '',
						'sub_fields' => array(
							array(
								'key' => 'field_65aae3730ec83',
								'label' => '',
								'name' => '',
								'aria-label' => '',
								'type' => 'clone',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_permissions' => '',
								'clone' => array(
									0 => 'group_65a993423b3e6',
								),
								'display' => 'seamless',
								'layout' => 'block',
								'prefix_label' => 0,
								'prefix_name' => 0,
								'acfe_settings' => '',
								'acfe_seamless_style' => 0,
								'acfe_clone_modal' => 0,
								'acfe_clone_modal_close' => 0,
								'acfe_clone_modal_button' => '',
								'acfe_clone_modal_size' => 'large',
							),
						),
						'acfe_group_modal' => 0,
						'acfe_group_modal_close' => 0,
						'acfe_group_modal_button' => '',
						'acfe_group_modal_size' => 'large',
					),
				),
				'acfe_seamless_style' => 0,
			),
			array(
				'key' => 'field_65aae00939f95',
				'label' => 'Options',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_permissions' => '',
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_65aae0093db93',
				'label' => 'Options',
				'name' => 'options',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_permissions' => '',
				'layout' => 'block',
				'acfe_seamless_style' => 1,
				'acfe_settings' => '',
				'acfe_group_modal' => 0,
				'acfe_group_modal_close' => 0,
				'acfe_group_modal_button' => '',
				'acfe_group_modal_size' => 'large',
				'sub_fields' => array(
					array(
						'key' => 'field_65aae00954a64',
						'label' => 'Self host video',
						'name' => 'self_host_video',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_65aae008cfde3',
									'operator' => '==',
									'value' => 'Video',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_permissions' => '',
						'message' => 'Self host this video instead of using vimeo?',
						'default_value' => 1,
						'acfe_settings' => '',
						'acfe_validate' => '',
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_65aae009584b2',
						'label' => '',
						'name' => '',
						'aria-label' => '',
						'type' => 'clone',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_permissions' => '',
						'clone' => array(
							0 => 'group_65a9931fafda9',
						),
						'display' => 'seamless',
						'layout' => 'block',
						'prefix_label' => 0,
						'prefix_name' => 0,
						'acfe_settings' => '',
						'acfe_seamless_style' => 0,
						'acfe_clone_modal' => 0,
						'acfe_clone_modal_close' => 0,
						'acfe_clone_modal_button' => '',
						'acfe_clone_modal_size' => 'large',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/header-block',
				),
			),
		),
		'menu_order' => -100,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'tooltip',
		'hide_on_screen' => array(
			0 => 'excerpt',
			1 => 'page_attributes',
			2 => 'featured_image',
			3 => 'categories',
			4 => 'tags',
		),
		'active' => true,
		'description' => '',
		'show_in_rest' => 1,
		'acfe_display_title' => '',
		'acfe_autosync' => '',
		'acfe_permissions' => '',
		'acfe_form' => 1,
		'acfe_meta' => '',
		'acfe_note' => '',
	) );

	acf_add_local_field_group( array(
		'key' => 'group_65a9b15bd0381',
		'title' => 'Page Settings',
		'fields' => array(
			array(
				'key' => 'field_65a9b15bd8719',
				'label' => 'Navbar Color settings',
				'name' => 'navbar_color_settings',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => 'Override the predefined Navigation Background and Link colors',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'transparent-dark' => 'Transparent Dark',
					'transparent-light' => 'Transparent Light',
					'primary' => 'primary',
					'secondary' => 'secondary',
					'info' => 'info',
					'error' => 'error',
					'success' => 'success',
					'dark' => 'dark',
					'light' => 'light',
					'rosey-red' => 'Rosey Red',
					'purple-durple' => 'purple durple',
					'durple' => 'durple',
				),
				'default_value' => 'transparent-dark',
				'return_format' => 'value',
				'multiple' => 0,
				'acfe_settings' => '',
				'acfe_validate' => '',
				'allow_null' => 0,
				'acfe_permissions' => '',
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'allow_custom' => 0,
				'search_placeholder' => '',
			),
			array(
				'key' => 'field_65a9b15bdc40d',
				'label' => 'Page Color scheme',
				'name' => 'background_color',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => 'Set the default page scheme',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => 'page_scheme',
				),
				'choices' => array(
					'primary' => 'primary',
					'secondary' => 'secondary',
					'info' => 'info',
					'error' => 'error',
					'success' => 'success',
					'dark' => 'dark',
					'light' => 'light',
					'rosey-red' => 'Rosey Red',
					'purple-durple' => 'purple durple',
					'durple' => 'durple',
				),
				'default_value' => 'light',
				'return_format' => 'value',
				'multiple' => 0,
				'placeholder' => '',
				'acfe_settings' => '',
				'acfe_validate' => '',
				'allow_null' => 1,
				'acfe_permissions' => '',
				'ui' => 0,
				'ajax' => 0,
				'allow_custom' => 0,
				'search_placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'all',
				),
				array(
					'param' => 'current_user',
					'operator' => '==',
					'value' => 'logged_in',
				),
				array(
					'param' => 'current_user',
					'operator' => '==',
					'value' => 'viewing_back',
				),
			),
		),
		'menu_order' => -50,
		'position' => 'side',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'tooltip',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'acfe_display_title' => '',
		'acfe_autosync' => '',
		'acfe_permissions' => '',
		'acfe_form' => 1,
		'acfe_meta' => '',
		'acfe_note' => '',
	) );

	acf_add_local_field_group( array(
		'key' => 'group_62fed1fb44be0',
		'title' => 'CTA Block',
		'fields' => array(
			array(
				'key' => 'field_62fed1fb7c051',
				'label' => 'CTA Title',
				'name' => 'cta_title',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_62fed1fb7fd7b',
				'label' => 'CTA Link',
				'name' => 'cta_link',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'page',
				),
				'taxonomy' => '',
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'object',
				'save_custom' => 0,
				'save_post_status' => 'publish',
				'acfe_bidirectional' => array(
					'acfe_bidirectional_enabled' => '0',
				),
				'ui' => 1,
				'save_post_type' => '',
			),
			array(
				'key' => 'field_62fed1fb83a6b',
				'label' => 'CTA Link Text',
				'name' => 'cta_link_text',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Leave blank to display the linked page title',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_65135977060e4',
				'label' => '',
				'name' => 'main_settings',
				'aria-label' => '',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'clone' => array(
					0 => 'group_62fd2d64375a9',
				),
				'display' => 'seamless',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 0,
				'acfe_seamless_style' => 0,
				'acfe_clone_modal' => 0,
				'acfe_clone_modal_close' => 0,
				'acfe_clone_modal_button' => '',
				'acfe_clone_modal_size' => 'large',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/supply-call-to-action',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'acfe_display_title' => '',
		'acfe_autosync' => '',
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
	) );

	acf_add_local_field_group( array(
		'key' => 'group_6337510d357a7',
		'title' => 'Featured Posts Block',
		'fields' => array(
			array(
				'key' => 'field_65138986b1a71',
				'label' => '(Column 8/12)',
				'name' => '',
				'aria-label' => '',
				'type' => 'acfe_column',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'columns' => '8/12',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_6337510d5da2d',
				'label' => 'Use default Loop',
				'name' => 'use_default_loop',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => 'This will load posts in the order they have been published',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Use the default post loop',
				'default_value' => 1,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_6337510d61679',
				'label' => 'Define your own loop',
				'name' => 'define_your_own_loop',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_6337510d5da2d',
							'operator' => '!=',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_repeater_stylised_button' => 0,
				'collapsed' => 'field_62e81035ec263',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Add a featured post',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_6337510d83402',
						'label' => 'Post',
						'name' => 'post',
						'aria-label' => '',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'post_type' => '',
						'taxonomy' => '',
						'allow_null' => 0,
						'multiple' => 0,
						'return_format' => 'id',
						'save_custom' => 0,
						'save_post_status' => 'publish',
						'acfe_bidirectional' => array(
							'acfe_bidirectional_enabled' => '0',
						),
						'ui' => 1,
						'save_post_type' => '',
						'parent_repeater' => 'field_6337510d61679',
					),
				),
			),
			array(
				'key' => 'field_651389ceb1a72',
				'label' => '(Column 4/12)',
				'name' => '',
				'aria-label' => '',
				'type' => 'acfe_column',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'columns' => '4/12',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_633c5ab899914',
				'label' => '',
				'name' => 'fold_settings',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'acfe_seamless_style' => 1,
				'acfe_group_modal' => 0,
				'acfe_group_modal_close' => 0,
				'acfe_group_modal_button' => '',
				'acfe_group_modal_size' => 'large',
				'sub_fields' => array(
					array(
						'key' => 'field_633c5a9f99913',
						'label' => 'fold',
						'name' => 'fold',
						'aria-label' => '',
						'type' => 'clone',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'clone' => array(
							0 => 'group_62e884077e396',
						),
						'display' => 'seamless',
						'layout' => 'block',
						'prefix_label' => 0,
						'prefix_name' => 0,
						'acfe_seamless_style' => 0,
						'acfe_clone_modal' => 0,
						'acfe_clone_modal_close' => 0,
						'acfe_clone_modal_button' => '',
						'acfe_clone_modal_size' => 'large',
					),
				),
			),
			array(
				'key' => 'field_6513884e7f38c',
				'label' => '',
				'name' => 'container_settings',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'acfe_seamless_style' => 1,
				'acfe_group_modal' => 0,
				'acfe_group_modal_close' => 0,
				'acfe_group_modal_button' => '',
				'acfe_group_modal_size' => 'large',
				'sub_fields' => array(
					array(
						'key' => 'field_6513884e7f38e',
						'label' => '',
						'name' => 'main_settings',
						'aria-label' => '',
						'type' => 'clone',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'clone' => array(
							0 => 'field_650fa810a0a66',
							1 => 'field_650fa810a0af7',
							2 => 'field_6511d1fee688d',
							3 => 'field_6511d21fe688e',
						),
						'display' => 'seamless',
						'layout' => 'block',
						'prefix_label' => 0,
						'prefix_name' => 0,
						'acfe_seamless_style' => 0,
						'acfe_clone_modal' => 0,
						'acfe_clone_modal_close' => 0,
						'acfe_clone_modal_button' => '',
						'acfe_clone_modal_size' => 'large',
					),
				),
			),
			array(
				'key' => 'field_651389dcb1a73',
				'label' => '(Column Endpoint)',
				'name' => '',
				'aria-label' => '',
				'type' => 'acfe_column',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'endpoint' => 1,
				'columns' => '6/12',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/supply-posts-block',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'acfe_display_title' => '',
		'acfe_autosync' => '',
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
	) );

	acf_add_local_field_group( array(
		'key' => 'group_65a190d7009be',
		'title' => 'Footer Nav Options',
		'fields' => array(
			array(
				'key' => 'field_65a190d743d50',
				'label' => '',
				'name' => '',
				'aria-label' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '<a href="/wp-admin/nav-menus.php?action=locations">You can edit the menu used for this block here.</a>',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_65a1917343d51',
				'label' => 'Navigation Stance',
				'name' => 'navigation_stance',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Display horizontal? (best for navs with sub-nav items)',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_65a1b6429d728',
				'label' => 'Justify',
				'name' => 'justify',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65a1917343d51',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'center' => 'center',
					'start' => 'start',
					'end' => 'end',
					'around' => 'around',
					'between' => 'between',
					'evenly' => 'evenly',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 1,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'allow_custom' => 0,
				'search_placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/footer-nav',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'acfe_display_title' => '',
		'acfe_autosync' => '',
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
	) );

	acf_add_local_field_group( array(
		'key' => 'group_65a993423b3e6',
		'title' => 'Image Options',
		'fields' => array(
			array(
				'key' => 'field_65a97b240d150',
				'label' => 'Make full screen?',
				'name' => 'make_full_screen',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Make this media block full screen?',
				'default_value' => 1,
				'acfe_settings' => '',
				'acfe_validate' => '',
				'acfe_permissions' => '',
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_65a20d83b056c',
				'label' => 'Turn on overlay',
				'name' => 'turn_on_overlay',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_permissions' => '',
				'message' => 'Activate a overlay?',
				'default_value' => 0,
				'ui' => 0,
				'acfe_settings' => '',
				'acfe_validate' => '',
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_65a9a4efde3b1',
				'label' => 'Opacity Level',
				'name' => 'opacity_level',
				'aria-label' => '',
				'type' => 'range',
				'instructions' => 'This is by percentage. Not be decimal.',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65a20d83b056c',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => 86,
				'min' => '',
				'max' => 99,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_65a9aa68d6402',
				'label' => 'Gradient Level',
				'name' => 'gradient_level',
				'aria-label' => '',
				'type' => 'range',
				'instructions' => 'This is by percentage. Not be decimal.',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65a20d83b056c',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => 45,
				'min' => '',
				'max' => 100,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_65a99532b8184',
				'label' => 'Overlay Color',
				'name' => 'overlay_color',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => 'enter hex code with \'#\' or entire a name of known color (lowercase), i.e. black, white, yellow, etc',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65a20d83b056c',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'primary' => 'primary',
					'secondary' => 'secondary',
					'info' => 'info',
					'error' => 'error',
					'success' => 'success',
					'dark' => 'dark',
					'light' => 'light',
				),
				'default_value' => 'dark',
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'allow_custom' => 0,
				'search_placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'comment',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'acfe_display_title' => '',
		'acfe_autosync' => '',
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
	) );

	acf_add_local_field_group( array(
		'key' => 'group_645d15ec9708b',
		'title' => 'Related Articles',
		'fields' => array(
			array(
				'key' => 'field_645d15ecb1e19',
				'label' => 'Use default Loop',
				'name' => 'use_default_loop',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => 'This will load posts in the order they have been published',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Use the default post loop',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_645d15ed665e1',
				'label' => 'Pick your related articles',
				'name' => 'related_post',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_645d15ecb1e19',
							'operator' => '!=',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'post',
				),
				'taxonomy' => '',
				'allow_null' => 0,
				'multiple' => 1,
				'return_format' => 'id',
				'save_custom' => 0,
				'save_post_status' => 'publish',
				'acfe_bidirectional' => array(
					'acfe_bidirectional_enabled' => '0',
				),
				'ui' => 1,
				'save_post_type' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'acfe_display_title' => '',
		'acfe_autosync' => '',
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
	) );

	acf_add_local_field_group( array(
		'key' => 'group_62fe8fa569a02',
		'title' => 'Seperator Block',
		'fields' => array(
			array(
				'key' => 'field_62fe9096a94dd',
				'label' => '',
				'name' => 'main_settings',
				'aria-label' => '',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'clone' => array(
					0 => 'group_62fd2d64375a9',
				),
				'display' => 'seamless',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 0,
				'acfe_seamless_style' => 0,
				'acfe_clone_modal' => 0,
				'acfe_clone_modal_close' => 0,
				'acfe_clone_modal_button' => '',
				'acfe_clone_modal_size' => 'large',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/supply-separator-block',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'acfe_display_title' => '',
		'acfe_autosync' => '',
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
	) );

	acf_add_local_field_group( array(
		'key' => 'group_65a194f941615',
		'title' => 'Social Media Nav Options',
		'fields' => array(
			array(
				'key' => 'field_65a194f94a728',
				'label' => '',
				'name' => '',
				'aria-label' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '<a href="/admin.php?page=theme_options">You can edit the menu used for this block here.</a>',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_65a194f94e1ca',
				'label' => 'Navigation Stance',
				'name' => 'navigation_stance',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Display Horizontal?',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/social-media-nav',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'acfe_display_title' => '',
		'acfe_autosync' => '',
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
	) );

	acf_add_local_field_group( array(
		'key' => 'group_62dab85823a87',
		'title' => 'Theme Options Page',
		'fields' => array(
			array(
				'key' => 'field_659c5dd4ca5d5',
				'label' => 'Theme Colors',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_659ed81df204c',
				'label' => 'Turn off colors',
				'name' => 'turn_off_colors',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Use only the colors in the stylesheet',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_659c5debca5d6',
				'label' => 'Primary Color',
				'name' => 'primary_color',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_659ed81df204c',
							'operator' => '!=',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#593196',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_659c5e9eca5d7',
				'label' => 'Secondary Color',
				'name' => 'secondary_color',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#A991D4',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_659c5ec3ca5db',
				'label' => 'Info Color',
				'name' => 'info_color',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#009CDC',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_659c5f00ca5dc',
				'label' => 'Error Color',
				'name' => 'error_color',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#FC3939',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_659c5f1bca5dd',
				'label' => 'Success Color',
				'name' => 'success_color',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#13B955',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_659c5f27ca5de',
				'label' => 'Dark Color',
				'name' => 'dark_color',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#000000',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_659c5f39ca5df',
				'label' => 'Light Color',
				'name' => 'light_color',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#ffffff',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_659de6cdb4e7c',
				'label' => 'gray-500',
				'name' => 'gray-500',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#adb5bd',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_659de6a2b4e7b',
				'label' => 'gray-600 (Gray)',
				'name' => 'gray-600',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#6c757d',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_659de6e6b4e7d',
				'label' => 'gray-800',
				'name' => 'gray-800',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#343a40',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_659de71fb4e7e',
				'label' => 'gray-900',
				'name' => 'gray-900',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#212529',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_659c6328cb672',
				'label' => 'Extra Colors',
				'name' => 'extra_colors',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_repeater_stylised_button' => 1,
				'layout' => 'table',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => 'field_659c6a4086b3b',
				'button_label' => 'Add Color',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_659c6a4086b3b',
						'label' => 'Color Label',
						'name' => 'color_label',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_659c6328cb672',
					),
					array(
						'key' => 'field_659c6a4986b3c',
						'label' => 'color',
						'name' => 'color',
						'aria-label' => '',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'enable_opacity' => 0,
						'return_format' => 'string',
						'parent_repeater' => 'field_659c6328cb672',
					),
				),
			),
			array(
				'key' => 'field_62dab863feaf0',
				'label' => 'Footer',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_62dabdf9ae263',
				'label' => 'Main footer settings',
				'name' => '',
				'aria-label' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'open' => 1,
				'multi_expand' => 0,
				'endpoint' => 0,
			),
			array(
				'key' => 'field_62dabe18ae264',
				'label' => 'Social Media options',
				'name' => '',
				'aria-label' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'open' => 0,
				'multi_expand' => 0,
				'endpoint' => 0,
			),
			array(
				'key' => 'field_62dabffa39ef7',
				'label' => 'Add a social Media account',
				'name' => 'add_a_social_media_account',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => 'Add Suuply\'s social links. The order that you add them here is the same order it will display on the frontend.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_repeater_stylised_button' => 0,
				'collapsed' => 'field_62dac05739ef9',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Add a Social Media account',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_62dac00f39ef8',
						'label' => 'Icon',
						'name' => 'icon',
						'aria-label' => '',
						'type' => 'font-awesome',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'icon_sets' => array(
							0 => 'solid',
							1 => 'regular',
							2 => 'brands',
						),
						'custom_icon_set' => '',
						'default_label' => '&lt;i class="fa-brands fa-instagram fa-fw"&gt;&lt;/i&gt; Instagram',
						'default_value' => '{ "style" : "brands", "id" : "instagram", "label" : "Instagram", "unicode" : "f16d" }',
						'save_format' => 'element',
						'allow_null' => 0,
						'show_preview' => 1,
						'enqueue_fa' => 0,
						'fa_live_preview' => '',
						'choices' => array(
						),
						'parent_repeater' => 'field_62dabffa39ef7',
					),
					array(
						'key' => 'field_62dac05739ef9',
						'label' => 'Social Media Name',
						'name' => 'social_media_name',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => 'This is for the alt text.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'Name of social media site ie: instagram',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'parent_repeater' => 'field_62dabffa39ef7',
					),
					array(
						'key' => 'field_62dac09539efa',
						'label' => 'URL',
						'name' => 'url',
						'aria-label' => '',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'parent_repeater' => 'field_62dabffa39ef7',
					),
				),
			),
			array(
				'key' => 'field_62e03aee74641',
				'label' => 'Social Media options (copy)',
				'name' => '',
				'aria-label' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'open' => 0,
				'multi_expand' => 0,
				'endpoint' => 1,
			),
			array(
				'key' => 'field_62e411a483779',
				'label' => 'Misc.',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_62e411b38377a',
				'label' => 'Nav Logos',
				'name' => 'nav_logos',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'acfe_seamless_style' => 0,
				'acfe_group_modal' => 0,
				'acfe_group_modal_close' => 0,
				'acfe_group_modal_button' => '',
				'acfe_group_modal_size' => 'large',
				'sub_fields' => array(
					array(
						'key' => 'field_62e411d48377b',
						'label' => 'Nav Dark',
						'name' => 'nav_dark',
						'aria-label' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'uploader' => '',
						'acfe_thumbnail' => 0,
						'return_format' => 'array',
						'preview_size' => 'medium',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'library' => 'all',
					),
					array(
						'key' => 'field_62e411f08377c',
						'label' => 'Nav Light',
						'name' => 'nav_light',
						'aria-label' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'uploader' => '',
						'acfe_thumbnail' => 0,
						'return_format' => 'array',
						'preview_size' => 'medium',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'library' => 'all',
					),
					array(
						'key' => 'field_6377e38b02fa2',
						'label' => 'SVG',
						'name' => 'svg',
						'aria-label' => '',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => '',
						'acfe_textarea_code' => 0,
					),
				),
			),
			array(
				'key' => 'field_62f182299893d',
				'label' => 'Background image',
				'name' => 'background_image',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => 'This should be a small pattern. This is currently configured to repeat it\'s self.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'uploader' => '',
				'acfe_thumbnail' => 0,
				'return_format' => 'url',
				'preview_size' => 'medium',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'library' => 'all',
			),
			array(
				'key' => 'field_64dfc946612c0',
				'label' => 'Service Offerings Image',
				'name' => 'offerings_image',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => 'This should be a small pattern. This is currently configured to repeat it\'s self.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'uploader' => '',
				'return_format' => 'url',
				'acfe_thumbnail' => 0,
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array(
				'key' => 'field_6397dbcb3eafb',
				'label' => 'Scroll Functions',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_6397dc093eafc',
				'label' => 'Top of Trigger Area',
				'name' => 'top_trigger_area',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Based off https://codepen.io/msamricth/pen/MWXdqEv',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '15%',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_6397dc4d3eafd',
				'label' => 'Bottom of Trigger Area',
				'name' => 'bottom_trigger_area',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Based off https://codepen.io/msamricth/pen/MWXdqEv',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '35%',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_6397dc7e3eafe',
				'label' => 'Transition Duriation',
				'name' => 'transition_duriation',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Format: 1s, 0.5s, 500ms',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '0.6s',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_6397dcaf3eaff',
				'label' => 'Transition type',
				'name' => 'transition_type',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'ease' => 'ease - Specifies an animation with a slow start, then fast, then end slowly (this is default)',
					'linear' => 'linear - Specifies an animation with the same speed from start to end',
					'ease-in' => 'ease-in - Specifies an animation with a slow start',
					'ease-out' => 'ease-out - Specifies an animation with a slow end',
					'ease-in-out' => 'ease-in-out	- Specifies an animation with a slow start and end',
				),
				'default_value' => 'ease',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
				'allow_custom' => 0,
				'search_placeholder' => '',
			),
			array(
				'key' => 'field_6397df4c7a73b',
				'label' => 'Actions that trigger the fold',
				'name' => 'scroll_fold_actions',
				'aria-label' => '',
				'type' => 'checkbox',
				'instructions' => 'Think scroll position',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'onEnter' => 'onEnter',
					'onLeave' => 'onLeave',
					'onLeaveBack' => 'onLeaveBack',
					'onEnterBack' => 'onEnterBack',
				),
				'allow_custom' => 0,
				'default_value' => array(
					0 => 'onEnter',
					1 => 'onEnterBack',
				),
				'layout' => 'vertical',
				'toggle' => 1,
				'return_format' => 'value',
				'save_custom' => 0,
				'custom_choice_button_text' => 'Add new choice',
			),
			array(
				'key' => 'field_6398ab24155d4',
				'label' => 'Reset',
				'name' => 'reset',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => 'Resets script to conditions laid out here: https://codepen.io/msamricth/pen/MWXdqEv',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Reset all fold fields here to development defaults',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_6398b33fd5012',
				'label' => 'Debug // Troubleshoot',
				'name' => 'debug_log',
				'aria-label' => '',
				'type' => 'checkbox',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'debugLog' => 'Turn on debug log (Developer console)',
					'debugMarker' => 'Turn on Debug Marker (On Page)',
					'videoMarker' => 'Turn on Video Marker (works best if you turn off debug marker)',
				),
				'allow_custom' => 0,
				'default_value' => array(
				),
				'layout' => 'vertical',
				'toggle' => 0,
				'return_format' => 'value',
				'save_custom' => 0,
				'custom_choice_button_text' => 'Add new choice',
			),
			array(
				'key' => 'field_6397df217a73a',
				'label' => 'Extensions',
				'name' => '',
				'aria-label' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Other site related animations/elements that are connected / activated by the fold',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_6397de7d7a739',
				'label' => 'Allow Custom Colors',
				'name' => 'allow_custom_colors',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'message' => 'Allow the use of custom colors',
				'default_value' => 1,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_6397e0bf7a73d',
				'label' => 'Turn on/off Nav Compress',
				'name' => 'nav_compression',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'message' => 'Hide nav when scrolling?',
				'default_value' => 1,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_6421dadbca311',
				'label' => 'Media Block',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_642dd2754e474',
				'label' => '(Column 6/12)',
				'name' => '',
				'aria-label' => '',
				'type' => 'acfe_column',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'columns' => '6/12',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_6421daf1ca312',
				'label' => 'Play Button',
				'name' => 'play_button',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'uploader' => '',
				'return_format' => 'url',
				'preview_size' => 'medium',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'acfe_thumbnail' => 0,
				'library' => 'all',
			),
			array(
				'key' => 'field_6421db3fca313',
				'label' => 'Mute Button',
				'name' => 'mute_button',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'uploader' => '',
				'return_format' => 'url',
				'preview_size' => 'medium',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'acfe_thumbnail' => 0,
				'library' => 'all',
			),
			array(
				'key' => 'field_6421db4dca314',
				'label' => 'UnMute Button',
				'name' => 'unmute_button',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'uploader' => '',
				'return_format' => 'url',
				'preview_size' => 'medium',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'acfe_thumbnail' => 0,
				'library' => 'all',
			),
			array(
				'key' => 'field_642dd2684e473',
				'label' => '(Column 6/12)',
				'name' => '',
				'aria-label' => '',
				'type' => 'acfe_column',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'columns' => '6/12',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_642dd29a4e477',
				'label' => 'Play Button (dark)',
				'name' => 'play_button_dark',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'uploader' => '',
				'return_format' => 'url',
				'preview_size' => 'medium',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'acfe_thumbnail' => 0,
				'library' => 'all',
			),
			array(
				'key' => 'field_642dd2884e476',
				'label' => 'Mute Button (dark)',
				'name' => 'mute_button_dark',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'uploader' => '',
				'return_format' => 'url',
				'preview_size' => 'medium',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'acfe_thumbnail' => 0,
				'library' => 'all',
			),
			array(
				'key' => 'field_642dd27d4e475',
				'label' => 'UnMute Button (dark)',
				'name' => 'unmute_button_dark',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'uploader' => '',
				'return_format' => 'url',
				'preview_size' => 'medium',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'acfe_thumbnail' => 0,
				'library' => 'all',
			),
			array(
				'key' => 'field_643d9d96b94df',
				'label' => '(Column Endpoint)',
				'name' => '',
				'aria-label' => '',
				'type' => 'acfe_column',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'endpoint' => 1,
				'columns' => '6/12',
			),
			array(
				'key' => 'field_643d9d1c3fa4a',
				'label' => '404 Page',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_643d9e7c0087c',
				'label' => '404 Page Settings',
				'name' => '404_page_settings',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'acfe_seamless_style' => 0,
				'acfe_group_modal' => 0,
				'acfe_group_modal_close' => 0,
				'acfe_group_modal_button' => '',
				'acfe_group_modal_size' => 'large',
				'sub_fields' => array(
					array(
						'key' => 'field_643d9d2c3fa4b',
						'label' => 'Title',
						'name' => '404_title',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_643d9d413fa4d',
						'label' => '404 CTA',
						'name' => '404_cta',
						'aria-label' => '',
						'type' => 'clone',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'clone' => array(
							0 => 'group_63f4f433d5b17',
						),
						'display' => 'seamless',
						'layout' => 'block',
						'prefix_label' => 0,
						'prefix_name' => 0,
						'acfe_seamless_style' => 0,
						'acfe_clone_modal' => 0,
						'acfe_clone_modal_close' => 0,
						'acfe_clone_modal_button' => '',
						'acfe_clone_modal_size' => 'large',
					),
				),
			),
			array(
				'key' => 'field_65a038a228652',
				'label' => 'Navigation',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_65a038b228653',
				'label' => 'Hamburger Animation',
				'name' => 'hamburger_animation',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => 'Select a hamburger animation for the nav in mobile. Based off of https://jonsuh.com/hamburgers/',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'slider' => 'slider',
					'squeeze' => 'squeeze',
					'arrow' => 'arrow',
					'arrow alt' => 'arrow alt',
					'arrow turn' => 'arrow turn',
					'spin' => 'spin',
					'elastic' => 'elastic',
					'emphatic' => 'emphatic',
					'collapse' => 'collapse',
					'vortex' => 'vortex',
					'stand' => 'stand',
					'spring' => 'spring',
					'minus' => 'minus',
					'3dx' => '3dx',
					'3dy' => '3dy',
					'3dxy' => '3dxy',
					'boring' => 'boring',
				),
				'default_value' => 'stand',
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'allow_custom' => 0,
				'search_placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'theme_options',
				),
			),
			array(
				array(
					'param' => 'post',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'tooltip',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'acfe_display_title' => '',
		'acfe_autosync' => '',
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
	) );

	acf_add_local_field_group( array(
		'key' => 'group_65a9931fafda9',
		'title' => 'Video Options',
		'fields' => array(
			array(
				'key' => 'field_65a97c5d0d161',
				'label' => 'Make Full Screen',
				'name' => 'make_full_screen',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Make the header full width & full height?',
				'default_value' => 1,
				'acfe_settings' => '',
				'acfe_validate' => '',
				'acfe_permissions' => '',
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_65a97c5d0d156',
				'label' => 'Ratio',
				'name' => 'video_ratio',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65a97c5d0d161',
							'operator' => '!=',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'21x9' => 'ratio-21x9',
					'16x9' => 'ratio-16x9',
					'4x3' => 'ratio-4x3',
					'3x2' => 'ratio-3x2',
				),
				'default_value' => '16x9',
				'return_format' => 'value',
				'multiple' => 0,
				'allow_custom' => 1,
				'search_placeholder' => '',
				'allow_null' => 0,
				'ui' => 1,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_65a99532ab8c6',
				'label' => 'Turn on overlay',
				'name' => 'turn_on_overlay',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_permissions' => '',
				'message' => 'Activate a overlay?',
				'default_value' => 0,
				'ui' => 0,
				'acfe_settings' => '',
				'acfe_validate' => '',
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_65a20d83b247c',
				'label' => 'Opacity Level',
				'name' => 'opacity_level',
				'aria-label' => '',
				'type' => 'range',
				'instructions' => 'This is by percentage. Not be decimal.',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65a99532ab8c6',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => 85,
				'min' => '',
				'max' => 99,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_65a9aa9576a34',
				'label' => 'Gradient Level',
				'name' => 'gradient_level',
				'aria-label' => '',
				'type' => 'range',
				'instructions' => 'This is by percentage. Not be decimal.',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65a99532ab8c6',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => 45,
				'min' => '',
				'max' => 100,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_65a9a8cfc95b5',
				'label' => 'Overlay Color',
				'name' => 'overlay_color',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => 'enter hex code with \'#\' or entire a name of known color (lowercase), i.e. black, white, yellow, etc',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65a99532ab8c6',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'primary' => 'primary',
					'secondary' => 'secondary',
					'info' => 'info',
					'error' => 'error',
					'success' => 'success',
					'dark' => 'dark',
					'light' => 'light',
				),
				'default_value' => 'dark',
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'allow_custom' => 0,
				'search_placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'comment',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'acfe_display_title' => '',
		'acfe_autosync' => '',
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
	) );
} );

